name: Test

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Wget PIO
        run: wget -O get-platformio.py https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py
      
      - name: Install PIO
        run: python3 get-platformio.py

      - name: Add path
        run: mkdir -p /usr/local/bin && ln -s ~/.platformio/penv/bin/pio /usr/local/bin/pio \

      - name: Check
        run: platformio check